apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xu8s7d3rt-java-quarkus 
  janus-idp.io/tekton: xu8s7d3rt-java-quarkus
  backstage.io/kubernetes-id: xu8s7d3rt-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xu8s7d3rt-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml